import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
type Process={id:string;name:string;status:string;demo:boolean;artifacts:string[];blockers:{message:string}[];analysis:any;runs:any[];jobs:any[];llm:any;discovery:any};
type State={processes:Process[];portfolio:Record<string,number|boolean>;token:string;capability:string;connections:Record<string,boolean>};
function App(){
 const [state,setState]=useState<State|null>(null),[selected,setSelected]=useState(''),[tab,setTab]=useState('Overview'),[events,setEvents]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [manifest,setManifest]=useState(''),[xlsx,setXlsx]=useState(''),[sources,setSources]=useState<Record<string,string>>({}),[prompt,setPrompt]=useState(''),[reviewer,setReviewer]=useState('');
 const p=state?.processes.find(p=>p.id===selected);
 async function refresh(){const r=await fetch('/api/state');if(!r.ok)throw Error('Cannot load workbench');setState(await r.json());}
 useEffect(()=>{let active=true;const poll=async()=>{try{const r=await fetch('/api/state');const d=await r.json();if(active)setState(d);}catch{if(active)setError('Connection unavailable. Restart the local application.');}};void poll();const t=setInterval(poll,1200);return()=>{active=false;clearInterval(t);};},[]);
 useEffect(()=>{if(!selected)return;let active=true;const poll=async()=>{try{const r=await fetch(`/api/process/${selected}/events`);const d=await r.json();if(active)setEvents(d);}catch{}};void poll();const t=setInterval(poll,1200);return()=>{active=false;clearInterval(t);};},[selected]);
 async function post(url:string,body:any={}){setBusy(true);setError('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':state?.token||''},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Operation failed');if(d.id)setSelected(d.id);await refresh();return d;}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function b64(file:File){const a=new Uint8Array(await file.arrayBuffer());let s='';for(const v of a)s+=String.fromCharCode(v);return btoa(s);}
 const link=(file:string)=>`/api/process/${p?.id}/artifact?path=${encodeURIComponent(file)}`;
 return <div className="shell"><aside><div className="brand">M<span>·</span>W</div><p className="eyebrow">MODERNIZATION WORKBENCH</p><h2>From source<br/>to evidence.</h2><button className="primary" disabled={busy||!state} onClick={()=>{setSelected('');setTab('Intake');}}>＋ New process</button><p className="label">PROCESSES</p>{state?.processes.map(x=><button key={x.id} className={'process '+(selected===x.id?'chosen':'')} onClick={()=>{setSelected(x.id);setTab('Overview');}}><strong>{x.name}</strong><small>{x.demo?'DEMO · ':''}{x.status.replaceAll('_',' ')}</small></button>)}<div className="asidebottom"><button disabled={busy||!state} onClick={()=>post('/api/demo')}>Run fictional example</button><p>Local · read-only discovery<br/>Python + SQLite target</p></div></aside>
 <main><header><div><p className="eyebrow">MAINFRAME → PYTHON</p><h1>{p?p.name:'Your modernization workspace'}</h1></div><span className="badge">{p?p.status.replaceAll('_',' '):'READY FOR INTAKE'}</span></header>{error&&<div role="alert" className="error">{error}</div>}
 <div className="metrics"><article><small>Production processes</small><b>{state?.portfolio.processes??0}</b></article><article><small>Unique program versions</small><b>{state?.portfolio.unique_program_versions??0}</b></article><article><small>Program memberships</small><b>{state?.portfolio.program_memberships??0}</b></article><article><small>Completed without blockers</small><b>{state?.portfolio.completed_processes??0}</b></article></div>
 <p className="scope">{state?.capability} Synthetic results are compared with source-derived expectations. Observed mainframe parity is not established.</p>
 <nav>{['Overview','Intake','Rules & lineage','SME review','Tests & reports','Setup'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
 {tab==='Intake'&&<section><h2>1. Provide the process and its source export</h2><p>Choose a Markdown job/step manifest or the Excel intake template, then select the matching Endeavor source files. Source files remain in this local workspace.</p><div className="fields"><label>Process manifest (.md or .xlsx)<input type="file" accept=".md,.xlsx" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.name.endsWith('.xlsx')){setXlsx(await b64(f));setManifest('');}else{setManifest(await f.text());setXlsx('');}}}/></label><label>Endeavor export (.cbl, .cpy, .jcl, .bms, .sql)<input type="file" multiple accept=".cbl,.cob,.cobol,.cpy,.copy,.jcl,.bms,.sql,.txt" onChange={async e=>{const files=Array.from(e.target.files||[]);if(files.length>200){setError('Maximum 200 files per process.');return;}const result:Record<string,string>={};for(const f of files){if(f.size>512000){setError('Source file exceeds 512 KB.');return;}if(result[f.name]){setError('Duplicate filenames need separate relative paths via API intake.');return;}result[f.name]=await f.text();}setSources(result);}}/></label></div><label>Analysis prompt (optional)<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Explain this process and identify assumptions to include in its one SME checklist."/></label><p>{Object.keys(sources).length} source files selected</p><button className="primary" disabled={busy||(!manifest&&!xlsx)||(!Object.keys(sources).length&&!state?.connections.local_source_export)} onClick={()=>post('/api/intake',{manifest,xlsx,sources,prompt}).then(d=>{if(d)setTab('Overview');})}>Create process</button></section>}
 {tab==='Overview'&&<section><div className="sectionhead"><h2>{p?'Execution timeline':'A clear path through the work'}</h2>{p&&<div>{p.status==='READY'&&<button className="primary" disabled={busy} onClick={()=>post(`/api/process/${p.id}/start`)}>Start</button>}{['PAUSED','FAILED','REPORTING_FAILED'].includes(p.status)&&<button disabled={busy} onClick={()=>post(`/api/process/${p.id}/resume`)}>Resume</button>}{!['READY','PAUSED','COMPLETED','COMPLETED_WITH_BLOCKERS'].includes(p.status)&&<button disabled={busy} onClick={()=>post(`/api/process/${p.id}/pause`)}>Pause</button>}</div>}</div><div className="stages">{['Intake','Source analysis','One SME review','Synthetic verification','Management report'].map((s,i)=><div key={s}><span>{i+1}</span><strong>{s}</strong></div>)}</div>{p?<div className="timeline">{events.map(e=><article key={e.seq}><small>{new Date(e.created).toLocaleTimeString()} · {e.stage}</small><p>{e.message}</p></article>)}</div>:<p>Upload the process inputs, click Start, hand the checklist to your SMEs, and import their answers. The local worker continues through tests and reports automatically.</p>}{p&&p.blockers.length>0&&<details open><summary>{p.blockers.length} unresolved blockers</summary>{p.blockers.map((b,i)=><p key={i} className="blocker">{b.message}</p>)}</details>}</section>}
 {tab==='Rules & lineage'&&<section><h2>Source rules and lineage</h2>{!p?.analysis?<p>Start analysis to see extracted rules.</p>:<><div className="lineage">{p.analysis.graph.map((g:any,i:number)=><div key={i}><strong>{g.from}</strong><span>→ {g.kind} →</span><strong>{g.to}</strong><small>{g.inputs?.join(', ')} → {g.outputs?.join(', ')}</small></div>)}</div><table><thead><tr><th>Rule</th><th>Plain-language behavior</th><th>Source evidence</th></tr></thead><tbody>{p.analysis.rules.map((r:any)=><tr key={r.id}><td>{r.id}</td><td>{r.plain}</td><td>{r.source_refs.join(', ')}</td></tr>)}</tbody></table><h3>Complete source-order accounting</h3>{Object.entries(p.analysis.source_accounting).map(([name,rows]:any)=><details key={name}><summary>{name}: {rows.length} source lines</summary><table><tbody>{rows.map((r:any)=><tr key={r.line}><td>{r.line}</td><td>{r.disposition}</td><td><code>{r.source}</code></td></tr>)}</tbody></table></details>)}</>}</section>}
 {tab==='SME review'&&<section><h2>One review packet. Simple answers.</h2><p>SMEs select Yes, No or Not sure for every row. For No, provide the correction. Unsupported behavior and unresolved answers remain recorded blockers; another questionnaire is not issued.</p>{p?.artifacts.filter(x=>x.startsWith('review/')&&!x.endsWith('.json')).map(x=><a className="download" key={x} href={link(x)}>Download {x.split('/').pop()}</a>)}{p?.status==='WAITING_SME'&&<div className="fields"><label>Reviewer name<input value={reviewer} onChange={e=>setReviewer(e.target.value)} /></label><label>Import completed checklist<input type="file" accept=".xlsx" disabled={!reviewer||busy} onChange={async e=>{const f=e.target.files?.[0];if(f)await post(`/api/process/${p.id}/answers`,{xlsx:await b64(f),reviewer});}}/></label></div>}</section>}
 {tab==='Tests & reports'&&<section><h2>Verification and management evidence</h2>{p?.runs.map((r:any)=><div key={r.id}><h3>{r.id} · {r.evidence_basis}</h3>{Object.entries(r.programs).map(([n,v]:any)=><p key={n}>{n}: {v.actual.length} cases · {v.differences.length} differences · branch coverage {v.coverage.complete?'complete':'has gaps'}</p>)}</div>)}<div className="downloads">{p?.artifacts.filter(x=>!x.startsWith('review/')).map(x=><a key={x} href={link(x)}>{x}</a>)}</div><p>Expected cases are frozen before Python execution. Workbook, CSV and PPT use the same metric snapshot. The deck contains editable tables.</p></section>}
 {tab==='Setup'&&<section><h2>Connection readiness</h2><p>Configuration is read from your local environment at startup. “Configured” does not prove that credentials or connectivity work.</p>{Object.entries(state?.connections||{}).map(([k,v])=><p key={k}><span className="dot"/>{k.replaceAll('_',' ')}: {v?'Configured':'Not configured'}</p>)}<p>Zowe: WB_ZOWE_PROFILE. Db2: WB_DB2_MCP_URL and WB_DB2_MCP_TOKEN. LLM: WB_LLM_URL, WB_LLM_MODEL, WB_LLM_TOKEN and explicit WB_ALLOW_SOURCE_EGRESS=true.</p><p>See START_HERE.md for the read-only Db2 adapter, connection contracts and local knowledge import locations.</p></section>}
 <footer>Evidence first · Demonstrations excluded from production totals · No mainframe execution</footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
