import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CoverageReport} from './CoverageReport';
import {SetupDiagnostics} from './SetupDiagnostics';
import {KnowledgePanel} from './KnowledgePanel';
import {readUtf8Source,readSourceFiles} from './intakeFiles';
type Process={id:string;name:string;status:string;demo:boolean;cancel_requested?:boolean;artifacts:string[];blockers:{message:string}[];analysis:any;mainframe_knowledge?:any;runs:any[];jobs:any[];llm:any;discovery:any};
type State={processes:Process[];portfolio:Record<string,number|boolean>;token:string;capability:string;connections:Record<string,boolean>};
function App(){
 const [state,setState]=useState<State|null>(null),[selected,setSelected]=useState(''),[tab,setTab]=useState('Overview'),[events,setEvents]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [manifest,setManifest]=useState(''),[xlsx,setXlsx]=useState(''),[sources,setSources]=useState<Record<string,string>>({}),[prompt,setPrompt]=useState(''),[reviewer,setReviewer]=useState('');
 const p=state?.processes.find(p=>p.id===selected);
 async function refresh(){const r=await fetch('/api/state');if(!r.ok)throw Error('Cannot load workbench');setState(await r.json());}
 useEffect(()=>{let active=true;const poll=async()=>{try{const r=await fetch('/api/state');if(!r.ok)throw Error('Connection unavailable');const d=await r.json();if(active){setState(d);setError(previous=>previous.startsWith('Connection unavailable.')?'':previous);}}catch{if(active)setError('Connection unavailable. Restart the local application.');}};void poll();const t=setInterval(poll,1200);return()=>{active=false;clearInterval(t);};},[]);
 useEffect(()=>{if(!selected)return;let active=true;const poll=async()=>{try{const r=await fetch(`/api/process/${selected}/events`);const d=await r.json();if(active)setEvents(d);}catch{}};void poll();const t=setInterval(poll,1200);return()=>{active=false;clearInterval(t);};},[selected]);
 async function post(url:string,body:any={}){setBusy(true);setError('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':state?.token||''},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||'Operation failed');if(d.id)setSelected(d.id);await refresh();return d;}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function b64(file:File){const a=new Uint8Array(await file.arrayBuffer());let s='';for(const v of a)s+=String.fromCharCode(v);return btoa(s);}

 const link=(file:string)=>`/api/process/${p?.id}/artifact?path=${encodeURIComponent(file)}`;
 return <div className="shell"><aside><div className="brand">M<span>·</span>W</div><p className="eyebrow">MODERNIZATION WORKBENCH</p><h2>From source<br/>to evidence.</h2><button className="primary" disabled={busy||!state} onClick={()=>{setSelected('');setTab('Intake');}}>＋ New process</button><p className="label">PROCESSES</p>{state?.processes.map(x=><button key={x.id} className={'process '+(selected===x.id?'chosen':'')} onClick={()=>{setSelected(x.id);setTab('Overview');}}><strong>{x.name}</strong><small>{x.demo?'DEMO · ':''}{x.status.replaceAll('_',' ')}</small></button>)}<div className="asidebottom"><button disabled={busy||!state} onClick={()=>post('/api/demo').then(d=>{if(d)setTab('Overview');})}>Run fictional example</button><p>Local · read-only discovery<br/>Python + SQLite target</p></div></aside>
 <main><header><div><p className="eyebrow">MAINFRAME → PYTHON</p><h1>{p?p.name:'Your modernization workspace'}</h1></div><span className="badge">{p?p.status.replaceAll('_',' '):'READY FOR INTAKE'}</span></header>{error&&<div role="alert" className="error">{error}</div>}
 <div className="metrics"><article><small>Production processes</small><b>{state?.portfolio.processes??0}</b></article><article><small>Unique program versions</small><b>{state?.portfolio.unique_program_versions??0}</b></article><article><small>Program memberships</small><b>{state?.portfolio.program_memberships??0}</b></article><article><small>Completed without blockers</small><b>{state?.portfolio.completed_processes??0}</b></article></div>
 <p className="scope">{state?.capability} Synthetic results are compared with source-derived expectations. Observed mainframe parity is not established.</p>
 <nav>{['Overview','Intake','Rules & lineage','Source coverage','Knowledge','SME review','Tests & reports','Setup'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
 {tab==='Intake'&&<section><h2>1. Provide the process and its source export</h2><p>Choose a Markdown job/step manifest or the Excel intake template, then select the matching Endeavor source files. Source files remain in this local workspace.</p><div className="fields"><label>Process manifest (.md or .xlsx)<input type="file" accept=".md,.xlsx" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.name.toLowerCase().endsWith('.xlsx')){if(f.size>2000000)throw Error('Intake workbook exceeds 2 MB.');setXlsx(await b64(f));setManifest('');}else{setManifest(await readUtf8Source(f,128000));setXlsx('');}setError('');}catch(error){setManifest('');setXlsx('');setError(String(error));}}}/></label><label>Endeavor text export (all file types)<input type="file" multiple onChange={async e=>{const files=Array.from(e.target.files||[]);try{const result=await readSourceFiles(files);setSources(result);setError('');}catch(error){setSources({});setError(String(error));}}}/></label></div><a className="download" href="/api/templates/intake">Download the editable Excel intake template</a><label>Analysis prompt (optional)<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Explain this process and identify assumptions to include in its one SME checklist."/></label><p>{Object.keys(sources).length?`${Object.keys(sources).length} source files selected`:'No uploaded files selected. The local Endeavor folder will be used when available.'}</p><button className="primary" disabled={busy||(!manifest&&!xlsx)||(!Object.keys(sources).length&&!state?.connections.local_source_export)} onClick={async()=>{const d=await post('/api/intake',{manifest,xlsx,...(Object.keys(sources).length?{sources}:{}),prompt});if(d){await post(`/api/process/${d.id}/start`);setTab('Overview');}}}>Start process</button></section>}
 {tab==='Overview'&&<section><div className="sectionhead"><h2>{p?'Execution timeline':'A clear path through the work'}</h2>{p&&<div>{p.status==='READY'&&<button className="primary" disabled={busy} onClick={()=>post(`/api/process/${p.id}/start`)}>Start</button>}{['PAUSED','FAILED','REPORTING_FAILED'].includes(p.status)&&<button disabled={busy} onClick={()=>post(`/api/process/${p.id}/resume`)}>Resume</button>}{!p.cancel_requested&&['QUEUED_ANALYSIS','ANALYZING','WAITING_SME','QUEUED_VERIFY','VERIFYING','QUEUED_REPORT','REPORTING'].includes(p.status)&&<button disabled={busy} onClick={()=>post(`/api/process/${p.id}/pause`)}>Pause</button>}{!p.cancel_requested&&!['COMPLETED','COMPLETED_WITH_BLOCKERS'].includes(p.status)&&<button disabled={busy} onClick={()=>post(`/api/process/${p.id}/cancel`)}>Cancel process</button>}</div>}</div><div className="stages">{['Intake','Source analysis','One SME review','Synthetic verification','Management report'].map((s,i)=><div key={s}><span>{i+1}</span><strong>{s}</strong></div>)}</div>{p?<div className="timeline">{events.map(e=><article key={e.seq}><small>{new Date(e.created).toLocaleTimeString()} · {e.stage}</small><p>{e.message}</p></article>)}</div>:<p>Upload the process inputs, click Start, hand the checklist to your SMEs, and import their answers. The local worker continues through tests and reports automatically.</p>}{p&&p.blockers.length>0&&<details open><summary>{p.blockers.length} unresolved blockers</summary>{p.blockers.map((b,i)=><p key={i} className="blocker">{b.message}</p>)}</details>}</section>}
 {tab==='Rules & lineage'&&<section><h2>Source rules and lineage</h2>{!p?.analysis?<p>Start analysis to see extracted rules.</p>:<><div className="lineage">{p.analysis.graph.map((g:any,i:number)=><div key={i}><strong>{g.from}</strong><span>→ {g.kind} →</span><strong>{g.to}</strong><small>{g.inputs?.join(', ')} → {g.outputs?.join(', ')}</small></div>)}</div><table><thead><tr><th>Rule</th><th>Plain-language behavior</th><th>Source evidence</th></tr></thead><tbody>{p.analysis.rules.map((r:any)=><tr key={r.id}><td>{r.id}</td><td>{r.plain}</td><td>{r.source_refs.join(', ')}</td></tr>)}</tbody></table><h3>Complete source-order accounting</h3>{Object.entries(p.analysis.source_accounting).map(([name,rows]:any)=><details key={name}><summary>{name}: {rows.length} source lines</summary><table><tbody>{rows.map((r:any)=><tr key={r.line}><td>{r.line}</td><td>{r.disposition}</td><td><code>{r.source}</code></td></tr>)}</tbody></table></details>)}</>}</section>}
 {tab==='Source coverage'&&<CoverageReport processId={p?.id} status={p?.status}/>}
 {tab==='Knowledge'&&<KnowledgePanel process={p}/>}
 {tab==='SME review'&&<section><h2>One review packet. Simple answers.</h2><p>SMEs select Yes, No or Not sure for every row. For No, provide the correction. Unsupported behavior and unresolved answers remain recorded blockers; another questionnaire is not issued.</p>{p?.artifacts.filter(x=>x.startsWith('review/')&&!x.endsWith('.json')).map(x=><a className="download" key={x} href={link(x)}>Download {x.split('/').pop()}</a>)}{p?.status==='WAITING_SME'&&<div className="fields"><label>Reviewer name<input value={reviewer} onChange={e=>setReviewer(e.target.value)} /></label><label>Import completed checklist<input type="file" accept=".xlsx" disabled={!reviewer||busy} onChange={async e=>{const f=e.target.files?.[0];if(f)try{if(f.size>8*1024*1024)throw Error('Returned workbook exceeds 8 MiB.');await post(`/api/process/${p.id}/answers`,{xlsx:await b64(f),reviewer});}catch(error){setError(String(error));}}}/></label></div>}</section>}
 {tab==='Tests & reports'&&<section><h2>Verification and management evidence</h2>{p?.runs.map((r:any)=><div key={r.id}><h3>{r.id} · {r.evidence_basis}</h3>{Object.entries(r.programs).map(([n,v]:any)=><p key={n}>{n}: {v.case_count??v.actual?.length??0} cases · {v.difference_count??v.differences?.length??0} differences · branch coverage {v.coverage.complete?'complete':'has gaps'}</p>)}</div>)}<div className="downloads">{p?.artifacts.filter(x=>!x.startsWith('review/')).map(x=><a key={x} href={link(x)}>{x}</a>)}</div><p>Expected cases are frozen before Python execution. Workbook, CSV and PPT use the same metric snapshot. The deck contains editable tables.</p></section>}
 {tab==='Setup'&&<SetupDiagnostics connections={state?.connections||{}}/>}
 <footer>Evidence first · Demonstrations excluded from production totals · No mainframe execution</footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
